version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - aws s3 cp target/cicd17-0.0.1-SNAPSHOT.jar s3://cicd17/cicdFolder/
artifacts:
  files:
    - target/*.jars
